
services:
  minnakapi:
    image: minnakapi
    build:
      context: .
      dockerfile: src/minnak.API/Dockerfile
    ports:
      - 5000:5000
    networks:
      - minnaknetwork


  minnakweb:
    image: minnakweb
    build:
      context: src/minnak.web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - minnaknetwork

networks:
  minnaknetwork:
    driver: bridge 
